roi = 72;
row = 10;
col = 1;
per = 0.01;
edgel = 0.03; edger = per; edgeh = per; edgeb = 0.05; space_h = per; space_v = per;
[pos]=subplot_pos(row,col,edgel,edger,edgeh,edgeb,space_h,space_v);

figure('units','normalized','outerposition',[0 0 1 1]);
sz = numel(a.tc_nonfilt(roi,:));
l = sz/4;
subplot('position',pos{1});
plot(a.tc_nonfilt(roi,1:l));legend('nonfilt');
subplot('position',pos{2});
plot(a.tc_filt(roi,1:l));legend('filt');
subplot('position',pos{3});
plot(a.tc_nonfilt_LC(roi,1:l));legend('nonfilt LC');
subplot('position',pos{4});
plot(a.tc_filt_LC(roi,1:l));legend('filt LC');
subplot('position',pos{5});
plot(a.tc_filt_dFoF(roi,1:l));legend('filt dFoF');
subplot('position',pos{6});
plot(a.tc_nonfilt_dFoF(roi,1:l));legend('nonfilt dFoF');
subplot('position',pos{7});
plot(a.tc_filt_LC_dFoF(roi,1:l));legend('filt LC dFoF');
subplot('position',pos{8});
plot(a.tc_nonfilt_LC_dFoF(roi,1:l));legend('nonfilt LC dFoF');
subplot('position',pos{9});
plot(a.spikes_LC(roi,1:l));legend('spikes LC');
subplot('position',pos{10});
plot(a.spikes(roi,1:l));legend('spikes');
